# Generated by Django 6.0.7 on 2026-08-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
